export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

// Brand Product
export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST'
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS'
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL'

// Categories product
export const CATEGORIES_LIST_REQUEST = 'CATEGORIES_LIST_REQUEST'
export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS'
export const CATEGORIES_LIST_FAIL = 'CATEGORIES_LIST_FAIL'

// Color Product
export const COLOR_LIST_REQUEST = 'COLOR_LIST_REQUEST'
export const COLOR_LIST_SUCCESS = 'COLOR_LIST_SUCCESS'
export const COLOR_LIST_FAIL = 'COLOR_LIST_FAIL'

// gender products
export const GENDER_LIST_REQUEST = 'GENDER_LIST_REQUEST'
export const GENDER_LIST_SUCCESS = 'GENDER_LIST_SUCCESS'
export const GENDER_LIST_FAIL = 'GENDER_LIST_FAIL'

// single product details
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

// product delete
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

// product create
export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

// product update
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

// create review
export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'
