const products = [
    // Nike
    {
        id: '1',
        img: '/images/img-1.jpg',
        brand: 'nike',
        name: 'Men White Flex Experience Run 10 Running Shoes',
        categories: 'shoes',
        price: 4995,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 40,
        numReviews: 5,
    },
    {
        id: '2',
        img: '/images/img-2.jpg',
        brand: 'nike',
        name: 'Men Black & Red ZOOM SPAN 3 Running Shoes',
        categories: 'shoes',
        price: 5396,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 5,
        countInStock: 40,
        numReviews: 8,
    },
    {
        id: '3',
        img: '/images/img-3.jpg',
        brand: 'nike',
        name: 'Women White AIR JORDAN 11 RETRO LOW Leather Basketball Shoes',
        categories: 'shoes',
        price: 15995,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 5,
        countInStock: 30,
        numReviews: 3,
    },
    {
        id: '4',
        img: '/images/img-4.jpg',
        brand: 'nike',
        name: 'Women Light Green Woven Design React Infinity FK 2 Running Shoes',
        categories: 'shoes',
        price: 14495,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 30,
        numReviews: 8,
    },
    {
        id: '5',
        img: '/images/img-5.jpg',
        brand: 'nike',
        name: 'Men Black Sustainable Flex Run 2021 Running Shoes',
        categories: 'shoes',
        price: 6794,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 40,
        numReviews: 9,
    },
    {
        id: '6',
        img: '/images/img-6.jpg',
        brand: 'nike',
        name: 'Men Grey Crater Remixa Sneakers',
        categories: 'shoes',
        price: 5495,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.5,
        countInStock: 50,
        numReviews: 5,
    },
    {
        id: '7',
        img: '/images/img-7.jpg',
        brand: 'nike',
        name: 'Men Charcoal Grey REACT PHANTOM FK 2 Running Shoes',
        categories: 'shoes',
        price: 11995,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 60,
        numReviews: 7,
    },
    {
        id: '8',
        img: '/images/img-8.jpg',
        brand: 'nike',
        name: 'Men White & Black ZOOM WINFLO 8 Running Shoes',
        categories: 'shoes',
        price: 8295,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 40,
        numReviews: 12,
    },
    {
        id: '9',
        img: '/images/img-9.jpg',
        brand: 'nike',
        name: "Men White Solid BLAZER LOW '77 VNTG Leather Sneakers",
        categories: 'shoes',
        price: 4.4,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 30,
        numReviews: 7,
    },
    {
        id: '10',
        img: '/images/img-10.jpg',
        brand: 'nike',
        name: 'Men Grey Crater Remixa Sneakers',
        categories: 'shoes',
        price: 5495,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.5,
        countInStock: 40,
        numReviews: 4,
    },
    {
        id: '11',
        img: '/images/img-11.jpg',
        brand: 'nike',
        name: 'Men Black Crater Remixa Sneakers',
        categories: 'shoes',
        price: 5495,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.5,
        countInStock: 30,
        numReviews: 6,
    },
    {
        id: '12',
        img: '/images/img-12.jpg',
        brand: 'nike',
        name: 'Men White COURT VISION Sneakers',
        categories: 'shoes',
        price: 4995,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 40,
        numReviews: 8,
    },
    {
        id: '13',
        img: '/images/img-13.jpg',
        brand: 'nike',
        name: "Men Black & White Blazer Low '77 Vintage Leather Sneakers",
        categories: 'shoes',
        price: 7195,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 50,
        numReviews: 6,
    },
    {
        id: '14',
        img: '/images/img-14.jpg',
        brand: 'nike',
        name: 'Men White Solid GTS 97 Sneakers',
        categories: 'shoes',
        price: 4995,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 20,
        numReviews: 3,
    },
    {
        id: '15',
        img: '/images/img-15.jpg',
        brand: 'nike',
        name: 'Women White BLAZER LOW SE Sneakers',
        categories: 'shoes',
        price: 3597,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 20,
        numReviews: 8,
    },
    {
        id: '16',
        img: '/images/img-16.jpg',
        brand: 'nike',
        name: 'Men Red Solid GTS 97 Sneakers',
        categories: 'shoes',
        price: 4995,
        color: 'red',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 30,
        numReviews: 6,
    },
    // Levis

    {
        id: '17',
        img: '/images/img-17.jpg',
        brand: 'Levis',
        name: 'Women Pink Solid Round Neck T-shirt With Front Knot',
        categories: 'kot',
        price: 699,
        color: 'pink',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 40,
        numReviews: 21,
    },
    {
        id: '18',
        img: '/images/img-18.jpg',
        brand: 'Levis',
        name: 'Men Black & Blue Printed Polo Collar T-shirt',
        categories: 'tshirt',
        price: 999,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 30,
        numReviews: 12,
    },
    {
        id: '19',
        img: '/images/img-19.jpg',
        brand: 'Levis',
        name: 'Men Black & Grey Striped Polo Collar T-shirt',
        categories: 'tshirt',
        price: 1099,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 40,
        numReviews: 10,
    },
    {
        id: '20',
        img: '/images/img-20.jpg',
        brand: 'Levis',
        name: 'Women White Printed Round Neck T-shirt',
        categories: 'tshirt',
        price: 699,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 60,
        numReviews: 12,
    },
    {
        id: '21',
        img: '/images/img-21.jpg',
        brand: 'Levis',
        name: 'Men Navy Blue Solid Polo Collar T-shirt',
        categories: 'tshirt',
        price: 1299,
        color: 'Navy-Blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 40,
        numReviews: 11,
    },
    {
        id: '22',
        img: '/images/img-22.jpg',
        brand: 'Levis',
        name: 'Women Olive Green Self Design Round Neck T-shirt',
        categories: 'tshirt',
        price: 1249,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 40,
        numReviews: 12,
    },
    {
        id: '23',
        img: '/images/img-23.jpg',
        brand: 'Levis',
        name: 'Men Olive Green Printed Polo Collar T-shirt',
        categories: 'tshirt',
        price: 2399,
        color: 'green',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 50,
        numReviews: 11,
    },
    {
        id: '24',
        img: '/images/img-24.jpg',
        brand: 'Levis',
        name: 'Women Olive Green Ribbed Round Neck T-shirt',
        categories: 'tshirt',
        price: 799,
        color: 'women',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 20,
        numReviews: 8,
    },
    {
        id: '25',
        img: '/images/img-25.jpg',
        brand: 'Levis',
        name: 'Men Black Solid Slim Fit Sustainable Stretchable Jeans',
        categories: 'jeans',
        price: 7999,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.9,
        countInStock: 50,
        numReviews: 8,
    },
    {
        id: '26',
        img: '/images/img-26.jpg',
        brand: 'Levis',
        name: 'Men Blue 65504 Skinny Fit Mid-Rise Highly Distressed Jeans',
        categories: 'jeans',
        price: 1799,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 38,
        numReviews: 8,
    },
    {
        id: '27',
        img: '/images/img-27.jpg',
        brand: 'Levis',
        name: 'Men Navy Blue 511 Slim Fit Mid-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 2799,
        color: 'navy-blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 66,
        numReviews: 15,
    },
    {
        id: '28',
        img: '/images/img-28.jpg',
        brand: 'Levis',
        name: 'Men Navy Blue 511 Slim Fit Mid-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 1949,
        color: 'navy-blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.1,
        countInStock: 44,
        numReviews: 21,
    },
    {
        id: '29',
        img: '/images/img-3.jpg',
        brand: 'Levis',
        name: 'Women Blue 311 Shaping Skinny Fit Mid-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 1799,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 55,
        numReviews: 17,
    },
    {
        id: '30',
        img: '/images/img-30.jpg',
        brand: 'Levis',
        name: 'Women Blue Revel Shaping Skinny Fit Mid-Rise Slash Knee Stretchable Jeans',
        categories: 'jeans',
        price: 2449,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 50,
        numReviews: 10,
    },
    {
        id: '31',
        img: '/images/img-31.jpg',
        brand: 'Levis',
        name: 'Women Blue 711 Skinny Fit Mid-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 1559,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 55,
        numReviews: 23,
    },
    {
        id: '32',
        img: '/images/img-32.jpg',
        brand: 'Levis',
        name: 'Women Charcoal Grey 311 Shaping Skinny Fit Mid-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 3599,
        color: 'grey',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.2,
        countInStock: 46,
        numReviews: 9,
    },
    {
        id: '33',
        img: '/images/img-33.jpg',
        brand: 'Levis',
        name: 'Women Blue 711 Skinny Fit Mid-Rise Clean Look Stretchable Waterless Jeans',
        categories: 'jeans',
        price: 1649,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 33,
        numReviews: 6,
    },
    {
        id: '34',
        img: '/images/img-34.jpg',
        brand: 'Levis',
        name: 'Men Blue Tapered Fit Mid-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 1949,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 70,
        numReviews: 15,
    },
    // Roadster

    {
        id: '35',
        img: '/images/img-35.jpg',
        brand: 'Roadster',
        name: 'Men White Brush Printed Round Neck T-shirt',
        categories: 'tshirt',
        price: 699,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 43,
        numReviews: 22,
    },
    {
        id: '36',
        img: '/images/img-36.jpg',
        brand: 'Roadster',
        name: 'Men Green & White Striped Pure Cotton T-Shirt',
        categories: 'tshirt',
        price: 314,
        color: 'green',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 40,
        numReviews: 10,
    },
    {
        id: '37',
        img: '/images/img-37.jpg',
        brand: 'Roadster',
        name: 'Men Orange Typography Printed T-shirt',
        categories: 'tshirt',
        price: 342,
        color: 'orange',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 55,
        numReviews: 12,
    },
    {
        id: '38',
        img: '/images/img-38.jpg',
        brand: 'Roadster',
        name: 'Men Green & Beige Checked Casual Shirt',
        categories: 'shirt',
        price: 679,
        color: 'green',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 55,
        numReviews: 12,
    },
    {
        id: '39',
        img: '/images/img-39.jpg',
        brand: 'Roadster',
        name: 'Men Black & White Regular Fit Checked Casual Shirt',
        categories: 'shirt',
        price: 749,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 30,
        numReviews: 10,
    },
    {
        id: '40',
        img: '/images/img-40.jpg',
        brand: 'Roadster',
        name: 'Women Grey Solid Extended Sleeves T-shirt',
        categories: 'tshirt',
        price: 359,
        color: 'grey',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 60,
        numReviews: 12,
    },
    {
        id: '41',
        img: '/images/img-41.jpg',
        brand: 'Roadster',
        name: 'Women Mustard Yellow Solid Round Neck T-shirt',
        categories: 'tshirt',
        price: 249,
        color: 'yellow',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 50,
        numReviews: 14,
    },
    {
        id: '42',
        img: '/images/img-42.jpg',
        brand: 'Roadster',
        name: 'Women Olive Green Solid Casual Shirt',
        categories: 'shirt',
        price: 519,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.5,
        countInStock: 40,
        numReviews: 9,
    },
    {
        id: '43',
        img: '/images/img-43.jpg',
        brand: 'Roadster',
        name: 'Women Black & White Regular Fit Striped Casual Shirt',
        categories: 'shirt',
        price: 666,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 33,
        numReviews: 5,
    },
    {
        id: '44',
        img: '/images/img-44.jpg',
        brand: 'Roadster',
        name: 'Women Mauve Solid Round Neck T-shirt',
        categories: 'tshirt',
        price: 239,
        color: 'mauve',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 66,
        numReviews: 30,
    },
    // Jack & Jones
    {
        id: '45',
        img: '/images/img-45.jpg',
        brand: 'Jack & Jones',
        name: 'Men Navy Blue Skinny Fit Low-Rise Stretchable Jeans',
        categories: 'jeans',
        price: 1649,
        color: 'navy blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 50,
        numReviews: 9,
    },
    {
        id: '46',
        img: '/images/img-46.jpg',
        brand: 'Jack & Jones',
        name: 'Men Blue LIAM Skinny Fit Low-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 1749,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 40,
        numReviews: 10,
    },
    {
        id: '47',
        img: '/images/img-47.jpg',
        brand: 'Jack & Jones',
        name: 'Men Blue Ben Skinny Fit Low-Rise Clean Look Stretchable Sustainable Jeans',
        categories: 'jeans',
        price: 1499,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 30,
        numReviews: 11,
    },
    {
        id: '48',
        img: '/images/img-48.jpg',
        brand: 'Jack & Jones',
        name: 'Men Blue Slim Fit Low-Rise Mildly Distressed Heavy Fade Stretchable Jeans',
        categories: 'jeans',
        price: 1749,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.9,
        countInStock: 30,
        numReviews: 12,
    },
    {
        id: '49',
        img: '/images/img-49.jpg',
        brand: 'Jack & Jones',
        name: 'Men Blue Clark Regular Fit Low Rise Mildly Distressed Jeans',
        categories: 'jeans',
        price: 1574,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.7,
        countInStock: 50,
        numReviews: 10,
    },
    {
        id: '50',
        img: '/images/img-50.jpg',
        brand: 'Jack & Jones',
        name: 'Men Blue Ben Skinny Fit Low-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 1499,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 30,
        numReviews: 3,
    },
    {
        id: '51',
        img: '/images/img-51.jpg',
        brand: 'Jack & Jones',
        name: 'Men Black Skinny Fit Low-Rise Stretchable Jeans',
        categories: 'jeans',
        price: 3499,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 55,
        numReviews: 10,
    },
    {
        id: '52',
        img: '/images/img-52.jpg',
        brand: 'Jack & Jones',
        name: 'Men Blue Slim Fit Low-Rise Stretchable Jeans',
        categories: 'jeans',
        price: 1499,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 30,
        numReviews: 5,
    },
    {
        id: '53',
        img: '/images/img-53.jpg',
        brand: 'Jack & Jones',
        name: 'Men Black & White Striped Slim Fit Casual Sustainable Shirt',
        categories: 'shirt',
        price: 1399,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 22,
        numReviews: 6,
    },
    {
        id: '54',
        img: '/images/img-54.jpg',
        brand: 'Jack & Jones',
        name: 'Men White & Black Slim Fit Self Design Casual Shirt',
        categories: 'shirt',
        price: 1649,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 33,
        numReviews: 12,
    },
    {
        id: '55',
        img: '/images/img-55.jpg',
        brand: 'Jack & Jones',
        name: 'Men Black Striped Polo Collar Sustainable T-shirt',
        categories: 'tshirt',
        price: 1679,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 44,
        numReviews: 12,
    },
    {
        id: '56',
        img: '/images/img-56.jpg',
        brand: 'Jack & Jones',
        name: 'Men Green & Black Checked Round Neck T-shirt',
        categories: 'tshirt',
        price: 1499,
        color: 'green',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 33,
        numReviews: 17,
    },
    {
        id: '57',
        img: '/images/img-57.jpg',
        brand: 'Jack & Jones',
        name: 'Men Multicoloured Dyed Round Neck T-shirt',
        categories: 'tshirt',
        price: 1499,
        color: 'dyed',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 20,
        numReviews: 9,
    },
    {
        id: '58',
        img: '/images/img-58.jpg',
        brand: 'Jack & Jones',
        name: 'Men White Solid Round Neck T-shirt with Printed Detail',
        categories: 'tshirt',
        price: 1799,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 44,
        numReviews: 12,
    },
    {
        id: '59',
        img: '/images/img-59.jpg',
        brand: 'Jack & Jones',
        name: 'Men Blue Slim Fit Solid Casual Shirt',
        categories: 'shirt',
        price: 2249,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 40,
        numReviews: 12,
    },
    {
        id: '60',
        img: '/images/img-60.jpg',
        brand: 'Jack & Jones',
        name: 'Men Rust Red Casual Corduroy Shirt',
        categories: 'shirt',
        price: 3499,
        color: 'red',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.7,
        countInStock: 33,
        numReviews: 12,
    },
    {
        id: '61',
        img: '/images/img-61.jpg',
        brand: 'Jack & Jones',
        name: 'Men Rust Red Slim Fit Solid Casual Shirt',
        categories: 'shirt',
        price: 1249,
        color: 'red',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 32,
        numReviews: 10,
    },
    // HRX by Hrithik Roshan
    {
        id: '62',
        img: '/images/img-62.jpg',
        brand: 'HRX',
        name: 'Men Blue & Charcoal Grey Colourblocked Rapid Dry Running T-shirt',
        categories: 'tshirt',
        price: 399,
        color: 'blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 33,
        numReviews: 24,
    },
    {
        id: '63',
        img: '/images/img-63.jpg',
        brand: 'HRX',
        name: 'Men Black Solid Rapid Dry Running Joggers',
        categories: 'joggers',
        price: 1050,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.9,
        countInStock: 54,
        numReviews: 15,
    },
    {
        id: '64',
        img: '/images/img-64.jpg',
        brand: 'HRX',
        name: 'Men Yellow Printed Round Neck T-Shirt',
        categories: 'tshirt',
        price: 699,
        color: 'yellow',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 32,
        numReviews: 21,
    },
    {
        id: '65',
        img: '/images/img-65.jpg',
        brand: 'HRX',
        name: 'Men Grey Front Runner Shoe',
        categories: 'shoes',
        price: 1709,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 64,
        numReviews: 13,
    },
    {
        id: '66',
        img: '/images/img-66.jpg',
        brand: 'HRX',
        name: 'Women Jet Black Solid Rapid-Dry Running T-shirt',
        categories: 'tshirt',
        price: 899,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 40,
        numReviews: 10,
    },
    {
        id: '67',
        img: '/images/img-67.jpg',
        brand: 'HRX',
        name: 'Men Black Solid Sporty Jacket',
        categories: 'jacket',
        price: 1559,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 43,
        numReviews: 12,
    },
    {
        id: '68',
        img: '/images/img-68.jpg',
        brand: 'HRX',
        name: 'Men Black Solid Joggers',
        categories: 'joggers',
        price: 899,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 33,
        numReviews: 11,
    },
    {
        id: '69',
        img: '/images/img-69.jpg',
        brand: 'HRX',
        name: 'Men Fluorescent Green Solid Round Neck Running T-shirt',
        categories: 'tshirt',
        price: 599,
        color: 'green',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.1,
        countInStock: 50,
        numReviews: 10,
    },
    {
        id: '70',
        img: '/images/img-70.jpg',
        brand: 'HRX',
        name: 'Men Grey Chunky Sneakers',
        categories: 'shoes',
        price: 2351,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 44,
        numReviews: 16,
    },
    {
        id: '71',
        img: '/images/img-71.jpg',
        brand: 'HRX',
        name: 'Men Black Slim Advanced Rapid Dry Raglan T-shirt',
        categories: 'tshirt',
        price: 599,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 43,
        numReviews: 23,
    },
    {
        id: '72',
        img: '/images/img-72.jpg',
        brand: 'HRX',
        name: 'Men Black Woven Design Street Running Shoes',
        categories: 'shoes',
        price: 1224,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 45,
        numReviews: 14,
    },
    {
        id: '73',
        img: '/images/img-73.jpg',
        brand: 'HRX',
        name: 'Men Black Advanced Rapid Dry Raglan Polo Collar T-shirt',
        categories: 'tshirt',
        price: 1299,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 34,
        numReviews: 8,
    },
    {
        id: '74',
        img: '/images/img-74.jpg',
        brand: 'HRX',
        name: 'Black Slim Rapid Dry Track Pants',
        categories: 'pants',
        price: 1499,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 45,
        numReviews: 13,
    },
    {
        id: '75',
        img: '/images/img-75.jpg',
        brand: 'HRX',
        name: 'Men Charcoal Grey Slim Advanced Rapid Dry Raglan T-shirt',
        categories: 'tshirt',
        price: 599,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 56,
        numReviews: 18,
    },
    {
        id: '76',
        img: '/images/img-76.jpg',
        brand: 'HRX',
        name: 'Men Navy Blue Solid T-shirt',
        categories: 'tshirt',
        price: 899,
        color: 'navy blue',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 54,
        numReviews: 14,
    },
    {
        id: '77',
        img: '/images/img-77.jpg',
        brand: 'HRX',
        name: 'Men Grey with Grindle Effect Round Neck RAPID-DRY T-shirt',
        categories: 'tshirt',
        price: 599,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.9,
        countInStock: 43,
        numReviews: 22,
    },
    // ONLY

    {
        id: '78',
        img: '/images/img-78.jpg',
        brand: 'ONLY',
        name: 'Women Green Mickey Mouse Printed Round Neck T-shirt',
        categories: 'tshirt',
        price: 899,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 43,
        numReviews: 12,
    },
    {
        id: '79',
        img: '/images/img-79.jpg',
        brand: 'ONLY',
        name: 'Women Off White & Black Striped Bodycon Dress',
        categories: 'dress',
        price: 1079,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 45,
        numReviews: 4,
    },
    {
        id: '80',
        img: '/images/img-80.jpg',
        brand: 'ONLY',
        name: 'Pink Regular Crop Top',
        categories: 'top',
        price: 2299,
        color: 'pink',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 54,
        numReviews: 14,
    },
    {
        id: '81',
        img: '/images/img-81.jpg',
        brand: 'ONLY',
        name: 'Women Mustard Yellow & White Regular Fit Printed Casual Shirt',
        categories: 'shirt',
        price: 1999,
        color: 'yellow',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 40,
        numReviews: 12,
    },
    {
        id: '82',
        img: '/images/img-82.jpg',
        brand: 'ONLY',
        name: 'Women Orange & White Printed Shirt Style Dress',
        categories: 'dress',
        price: 2699,
        color: 'orange',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.9,
        countInStock: 43,
        numReviews: 12,
    },
    {
        id: '83',
        img: '/images/img-83.jpg',
        brand: 'ONLY',
        name: 'Women Blue LU Carrot Fit High-Rise Low Distress Jeans with a Chain',
        categories: 'jeans',
        price: 3999,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 50,
        numReviews: 15,
    },
    {
        id: '84',
        img: '/images/img-84.jpg',
        brand: 'ONLY',
        name: 'Mustard Yellow Solid Top',
        categories: 'top',
        price: 1999,
        color: 'yellow',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 5,
        countInStock: 30,
        numReviews: 17,
    },
    {
        id: '85',
        img: '/images/img-85.jpg',
        brand: 'ONLY',
        name: 'Women Blue Skinny Fit Mid-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 3699,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 40,
        numReviews: 24,
    },
    {
        id: '86',
        img: '/images/img-86.jpg',
        brand: 'ONLY',
        name: 'Women Blue Solid Basic Jumpsuit',
        categories: 'jumpsuit',
        price: 1999,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 50,
        numReviews: 13,
    },
    {
        id: '87',
        img: '/images/img-87.jpg',
        brand: 'ONLY',
        name: 'Women Blue Relaxed Fit High-Rise Clean Look Jeans',
        categories: 'jeans',
        price: 2799,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 43,
        numReviews: 11,
    },
    {
        id: '88',
        img: '/images/img-88.jpg',
        brand: 'ONLY',
        name: 'Women Teal Blue Solid A-Line Dress',
        categories: 'dress',
        price: 3499,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 67,
        numReviews: 13,
    },
    {
        id: '89',
        img: '/images/img-89.jpg',
        brand: 'ONLY',
        name: 'Lime Green & Black Printed Button Closure A-Line Dress',
        categories: 'dress',
        price: 1264,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 43,
        numReviews: 16,
    },
    {
        id: '90',
        img: '/images/img-90.jpg',
        brand: 'ONLY',
        name: 'Women Olive Green Solid Gathered A-Line Dress',
        categories: 'dress',
        price: 4399,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 53,
        numReviews: 12,
    },
    {
        id: '91',
        img: '/images/img-91.jpg',
        brand: 'ONLY',
        name: 'Women Blue Regular Fit Mid-Rise Low Distress Stretchable Jeans',
        categories: 'jeans',
        price: 3145,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 65,
        numReviews: 12,
    },
    {
        id: '92',
        img: '/images/img-92.jpg',
        brand: 'ONLY',
        name: 'Women Black Skinny Fit Mid-Rise Clean Look Stretchable Jeans',
        categories: 'jeans',
        price: 1999,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 44,
        numReviews: 2,
    },
    // Anouk

    {
        id: '93',
        img: '/images/img-93.jpg',
        brand: 'Anouk',
        name: 'Women Pink Printed Straight Kurta',
        categories: 'kurta',
        price: 1799,
        color: 'pink',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 54,
        numReviews: 12,
    },
    {
        id: '94',
        img: '/images/img-94.jpg',
        brand: 'Anouk',
        name: 'Women Orange & Green Printed Straight Kurta',
        categories: 'kurta',
        price: 899,
        color: 'orange',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.1,
        countInStock: 24,
        numReviews: 6,
    },
    {
        id: '95',
        img: '/images/img-95.jpg',
        brand: 'Anouk',
        name: 'Women Green & Mustard Ethnic Motifs Printed A-Line Kurta',
        categories: 'kurta',
        price: 1319,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 40,
        numReviews: 7,
    },
    {
        id: '96',
        img: '/images/img-96.jpg',
        brand: 'Anouk',
        name: 'Navy Blue Striped Rayon Straight Kurta With Pompom Lace Hem',
        categories: 'kurta',
        price: 1599,
        color: 'navy blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 30,
        numReviews: 3,
    },
    {
        id: '97',
        img: '/images/img-97.jpg',
        brand: 'Anouk',
        name: 'Women Sea Green & Off-White Ikat Printed Straight Kurta',
        categories: 'kurta',
        price: 999,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 30,
        numReviews: 9,
    },
    {
        id: '98',
        img: '/images/img-98.jpg',
        brand: 'Anouk',
        name: 'Women Black & White Striped Straight Kurta',
        categories: 'kurta',
        price: 1599,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 40,
        numReviews: 22,
    },
    {
        id: '99',
        img: '/images/img-99.jpg',
        brand: 'Anouk',
        name: 'Women Off-White & Navy Printed A-Line Kurta',
        categories: 'kurta',
        price: 1079,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 30,
        numReviews: 11,
    },
    {
        id: '100',
        img: '/images/img-100.jpg',
        brand: 'Anouk',
        name: 'Women Red & White Ethnic Motifs Printed Block Print Kurta',
        categories: 'kurta',
        price: 699,
        color: 'red',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 30,
        numReviews: 7,
    },
    {
        id: '111',
        img: '/images/img-111.jpg',
        brand: 'Anouk',
        name: 'Navy Blue & Pink Silk Blend Embroidered Saree',
        categories: 'saree',
        price: 1399,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 44,
        numReviews: 12,
    },
    {
        id: '112',
        img: '/images/img-112.jpg',
        brand: 'Anouk',
        name: 'Blue & Grey Linen Blend Striped Saree',
        categories: 'saree',
        price: 1299,
        color: 'grey',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 30,
        numReviews: 10,
    },
    {
        id: '113',
        img: '/images/img-113.jpg',
        brand: 'Anouk',
        name: 'Magenta & Green Ethnic Motifs Woven Design Banarasi Saree',
        categories: 'saree',
        price: 1599,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 43,
        numReviews: 12,
    },
    {
        id: '114',
        img: '/images/img-114.jpg',
        brand: 'Anouk',
        name: 'Black & Red Pure Georgette Embroidered Saree',
        categories: 'saree',
        price: 3999,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 32,
        numReviews: 12,
    },
    {
        id: '115',
        img: '/images/img-115.jpg',
        brand: 'Anouk',
        name: 'Grey & Gold-Toned Silk Blend Embroidered Sequinned Saree',
        categories: 'saree',
        price: 1569,
        color: 'grey',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.2,
        countInStock: 29,
        numReviews: 7,
    },
    {
        id: '116',
        img: '/images/img-116.jpg',
        brand: 'Anouk',
        name: 'Red & White Pure Georgette Printed Bandhani Saree',
        categories: 'saree',
        price: 2399,
        color: 'red',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 40,
        numReviews: 12,
    },
    {
        id: '117',
        img: '/images/img-117.jpg',
        brand: 'Anouk',
        name: 'Off-White & Green Linen Blend Printed Bhagalpuri Saree',
        categories: 'saree',
        price: 1399,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 32,
        numReviews: 12,
    },
    {
        id: '118',
        img: '/images/img-118.jpg',
        brand: 'Anouk',
        name: 'Yellow & Orange Floral Celebrity Organza Saree',
        categories: 'saree',
        price: 1299,
        color: 'orange',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.6,
        countInStock: 54,
        numReviews: 14,
    },
    // M.A.C
    {
        id: '119',
        img: '/images/img-119.jpg',
        brand: 'M.A.C',
        name: 'Studio Fix SPF 15 Fluid Foundation - NC30 30ml',
        categories: 'beauty',
        price: 3999,
        color: 'fluid',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 44,
        numReviews: 14,
    },
    {
        id: '120',
        img: '/images/img-120.jpg',
        brand: 'M.A.C',
        name: 'Pro Longwear Fluidline Eyeliner and Brow Gel - Blacktrack 3 g',
        categories: 'beauty',
        price: 1700,
        color: 'brow',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 30,
        numReviews: 5,
    },
    {
        id: '121',
        img: '/images/img-121.jpg',
        brand: 'M.A.C',
        name: 'Powder Kiss Lipstick - Burning Love 305',
        categories: 'beauty',
        price: 1700,
        color: 'creem',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 54,
        numReviews: 13,
    },
    {
        id: '122',
        img: '/images/img-122.jpg',
        brand: 'M.A.C',
        name: 'Glow Play Blush - Totally Synced',
        categories: 'beauty',
        price: 2900,
        color: 'glow',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.8,
        countInStock: 55,
        numReviews: 24,
    },
    {
        id: '123',
        img: '/images/img-123.jpg',
        brand: 'M.A.C',
        name: 'Mini Lip Glass - Candy Box 2.4 g',
        categories: 'beauty',
        price: 1050,
        color: 'mini',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 40,
        numReviews: 21,
    },
    {
        id: '124',
        img: '/images/img-124.jpg',
        brand: 'M.A.C',
        name: 'Lip Pencil - Hover 1.4g',
        categories: 'beauty',
        price: 1650,
        color: 'lip',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 40,
        numReviews: 12,
    },
    {
        id: '125',
        img: '/images/img-125.jpg',
        brand: 'M.A.C',
        name: 'Powder Kiss Liquid Lipcolour - Resort Season 5 ml',
        categories: 'beauty',
        price: 2459,
        color: 'powder',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.4,
        countInStock: 44,
        numReviews: 20,
    },
    {
        id: '126',
        img: '/images/img-126.jpg',
        brand: 'M.A.C',
        name: 'Mini Matte Lipstick - Ruby Woo 1.8 g',
        categories: 'beauty',
        price: 1099,
        color: 'mini',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 40,
        numReviews: 19,
    },
    {
        id: '127',
        img: '/images/img-127.jpg',
        brand: 'M.A.C',
        name: 'Studio Fix Perfecting Loose Powder - Extra Light 8 g',
        categories: 'beauty',
        price: 2999,
        color: 'powder',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 30,
        numReviews: 8,
    },
    {
        id: '128',
        img: '/images/img-128.jpg',
        brand: 'M.A.C',
        name: 'Studio Fix Powder Plus Foundation - C4 15g',
        categories: 'beauty',
        price: 2999,
        color: 'powder',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 50,
        numReviews: 17,
    },
    {
        id: '129',
        img: '/images/img-129.jpg',
        brand: 'M.A.C',
        name: 'M.A.C. Studio Fix 24-Hour Smooth Wear Concealer - NC40',
        categories: 'beauty',
        price: 2499,
        color: 'concealer',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.9,
        countInStock: 40,
        numReviews: 19,
    },
    {
        id: '130',
        img: '/images/img-130.jpg',
        brand: 'M.A.C',
        name: 'Longwear Lip Pencil - Vino Pro 1.45 g',
        categories: 'beauty',
        price: 1699,
        color: 'lip',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 5,
        countInStock: 30,
        numReviews: 10,
    },
    {
        id: '131',
        img: '/images/img-131.jpg',
        brand: 'M.A.C',
        name: 'Matte Lipstick - Mehr',
        categories: 'beauty',
        price: 1700,
        color: 'lip',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 44,
        numReviews: 18,
    },
    {
        id: '132',
        img: '/images/img-132.jpg',
        brand: 'M.A.C',
        name: 'Mineralize Skinfinish Natural Compact - Medium Golden',
        categories: 'beauty',
        price: 3200,
        color: 'compact',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 20,
        numReviews: 11,
    },
    {
        id: '133',
        img: '/images/img-133.jpg',
        brand: 'M.A.C',
        name: 'Matte Lipstick - Velvet Teddy 3 gm',
        categories: 'beauty',
        price: 1799,
        color: 'lip',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 30,
        numReviews: 8,
    },
    {
        id: '134',
        img: '/images/img-134.jpg',
        brand: 'M.A.C',
        name: 'Studio Finish Concealer with SPF 35 - NC20 7g',
        categories: 'beauty',
        price: 2399,
        color: 'concealer',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 43,
        numReviews: 15,
    },
    // W
    {
        id: '135',
        img: '/images/img-135.jpg',
        brand: 'W',
        name: 'Women Blue Dyed A-Line Dress',
        categories: 'dress',
        price: 2999,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 60,
        numReviews: 12,
    },
    {
        id: '136',
        img: '/images/img-136.jpg',
        brand: 'W',
        name: 'Women Yellow Solid Empire Dress',
        categories: 'dress',
        price: 3999,
        color: 'yellow',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.9,
        countInStock: 40,
        numReviews: 11,
    },
    {
        id: '137',
        img: '/images/img-137.jpg',
        brand: 'W',
        name: 'Women Yellow Solid A-Line Dress',
        categories: 'dress',
        price: 2699,
        color: 'yellow',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 20,
        numReviews: 3,
    },
    {
        id: '138',
        img: '/images/img-138.jpg',
        brand: 'W',
        name: 'Women Cream-Coloured & Maroon Printed Anarkali Maxi Dress',
        categories: 'dress',
        price: 4299,
        color: 'cream',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3,
        countInStock: 37,
        numReviews: 3,
    },
    {
        id: '139',
        img: '/images/img-139.jpg',
        brand: 'W',
        name: 'Women Sea Green Printed Viscose Rayon Maxi Dress',
        categories: 'dress',
        price: 3599,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.5,
        countInStock: 35,
        numReviews: 8,
    },
    {
        id: '140',
        img: '/images/img-140.jpg',
        brand: 'W',
        name: 'Women Blue Colourblocked Fit and Flare Dress',
        categories: 'dress',
        price: 2999,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.4,
        countInStock: 20,
        numReviews: 3,
    },
    {
        id: '141',
        img: '/images/img-141.jpg',
        brand: 'W',
        name: 'Women Green Printed Maxi Dress',
        categories: 'dress',
        price: 4599,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.9,
        countInStock: 38,
        numReviews: 7,
    },
    {
        id: '142',
        img: '/images/img-142.jpg',
        brand: 'W',
        name: 'Women Navy Blue Solid A-Line Layered Dress',
        categories: 'dress',
        price: 999,
        color: 'navy blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.9,
        countInStock: 40,
        numReviews: 11,
    },
    {
        id: '143',
        img: '/images/img-143.jpg',
        brand: 'W',
        name: 'Women Black & White Monochrome Regular Crop Top',
        categories: 'top',
        price: 1999,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 49,
        numReviews: 12,
    },
    {
        id: '144',
        img: '/images/img-144.jpg',
        brand: 'W',
        name: 'Grey & Cream-Coloured Colourblocked Tie-Up Neck A-Line Top',
        categories: 'top',
        price: 1899,
        color: 'grey',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 35,
        numReviews: 11,
    },
    {
        id: '145',
        img: '/images/img-145.jpg',
        brand: 'W',
        name: 'Women Off White Printed A-line Top',
        categories: 'top',
        price: 1799,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 39,
        numReviews: 12,
    },
    {
        id: '146',
        img: '/images/img-146.jpg',
        brand: 'W',
        name: 'Navy Blue & Off White Printed Tie-up Neck Regular Top',
        categories: 'top',
        price: 999,
        color: 'navy blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 40,
        numReviews: 14,
    },
    {
        id: '147',
        img: '/images/img-147.jpg',
        brand: 'W',
        name: 'Women Yellow Tie-up Neck A-line Top',
        categories: 'top',
        price: 1899,
        color: 'yellow',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 45,
        numReviews: 16,
    },
    {
        id: '148',
        img: '/images/img-148.jpg',
        brand: 'W',
        name: 'Women Black and Silver Embellished Ethnic Crop Top',
        categories: 'top',
        price: 1125,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 59,
        numReviews: 18,
    },
    {
        id: '149',
        img: '/images/img-149.jpg',
        brand: 'W',
        name: 'Off White & Golden Floral Embellished Regular Crop Top',
        categories: 'top',
        price: 1899,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 30,
        numReviews: 8,
    },
    {
        id: '150',
        img: '/images/img-150.jpg',
        brand: 'W',
        name: ' Women Off White Striped Tie-up Neck A-line Top',
        categories: 'top',
        price: 1424,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 43,
        numReviews: 20,
    },
    // H&M

    {
        id: '151',
        img: '/images/img-151.jpg',
        brand: 'H&M',
        name: 'Men White Solid Relaxed Fit Sweatshirt',
        categories: 'sweatshirt',
        price: 799,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 60,
        numReviews: 17,
    },
    {
        id: '152',
        img: '/images/img-152.jpg',
        brand: 'H&M',
        name: 'Men Grey Solid Regular Fit Sweatshirt Shorts',
        categories: 'shorts',
        price: 799,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.6,
        countInStock: 44,
        numReviews: 6,
    },
    {
        id: '153',
        img: '/images/img-153.jpg',
        brand: 'H&M',
        name: 'Men White Printed Cotton T-shirt',
        categories: 'tshirt',
        price: 599,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.8,
        countInStock: 59,
        numReviews: 8,
    },
    {
        id: '154',
        img: '/images/img-154.jpg',
        brand: 'H&M',
        name: 'Men Black & White Looney Tunes Patterned Trainers',
        categories: 'shoes',
        price: 1999,
        color: 'black',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 50,
        numReviews: 10,
    },
    {
        id: '155',
        img: '/images/img-155.jpg',
        brand: 'H&M',
        name: 'Men White Printed Hooded Top',
        categories: 'top',
        price: 1609,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.7,
        countInStock: 30,
        numReviews: 9,
    },
    {
        id: '156',
        img: '/images/img-156.jpg',
        brand: 'H&M',
        name: 'Men White Solid 3-Pack T-shirts Slim Fit',
        categories: 'tshirt',
        price: 1499,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 40,
        numReviews: 12,
    },
    {
        id: '157',
        img: '/images/img-157.jpg',
        brand: 'H&M',
        name: 'Men Grey & Black Printed Cotton T-shirt',
        categories: 'tshirt',
        price: 799,
        color: 'grey',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 30,
        numReviews: 11,
    },
    {
        id: '158',
        img: '/images/img-158.jpg',
        brand: 'H&M',
        name: 'Men White Low Profile Looney Tunes Printed Trainers',
        categories: 'shoes',
        price: 1999,
        color: 'white',
        gender: 'men',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.5,
        countInStock: 60,
        numReviews: 15,
    },
    {
        id: '159',
        img: '/images/img-159.jpg',
        brand: 'H&M',
        name: 'Women Brown Short Jersey Top',
        categories: 'top',
        price: 399,
        color: 'brown',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 50,
        numReviews: 13,
    },
    {
        id: '160',
        img: '/images/img-160.jpg',
        brand: 'H&M',
        name: 'Women Blue Solid Cropped Top',
        categories: 'top',
        price: 399,
        color: 'blue',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4,
        countInStock: 44,
        numReviews: 12,
    },
    {
        id: '161',
        img: '/images/img-161.jpg',
        brand: 'H&M',
        name: 'Women Black Cotton dress',
        categories: 'dress',
        price: 1299,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 3.3,
        countInStock: 40,
        numReviews: 12,
    },
    {
        id: '162',
        img: '/images/img-162.jpg',
        brand: 'H&M',
        name: 'Women White Short Strappy Top',
        categories: 'top',
        price: 299,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.3,
        countInStock: 34,
        numReviews: 11,
    },
    {
        id: '163',
        img: '/images/img-163.jpg',
        brand: 'H&M',
        name: 'Women Black & Red Cotton Printed Cropped Top',
        categories: 'top',
        price: 699,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.4,
        countInStock: 77,
        numReviews: 23,
    },
    {
        id: '164',
        img: '/images/img-164.jpg',
        brand: 'H&M',
        name: 'Women White Ribbed Cropped Top',
        categories: 'top',
        price: 699,
        color: 'white',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.1,
        countInStock: 44,
        numReviews: 3,
    },
    {
        id: '165',
        img: '/images/img-165.jpg',
        brand: 'H&M',
        name: 'Women Black Solid Ribbed Cropped Top',
        categories: 'top',
        price: 699,
        color: 'black',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 4.9,
        countInStock: 66,
        numReviews: 18,
    },
    {
        id: '166',
        img: '/images/img-166.jpg',
        brand: 'H&M',
        name: 'Women Olive Green Ribbed Stand-up Collar Dress',
        categories: 'dress',
        price: 1499,
        color: 'green',
        gender: 'women',
        description:
            'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat iste fugit in suscipit.',
        rating: 5,
        countInStock: 55,
        numReviews: 15,
    },
]
export default products
